# Data Types - Synopsis

In this unit we will learn that:

1. Creating Variables
2. Basic data types of variables
3. Arithematic operations on variables
4. Type casting - Changing the data type of variables
5. Indexing and slicing

## Different data, different variable types

Data come in many formats. It can be a number, a piece of text, an image.  In order to write readable, efficient code it is important to create variables that match the nature of the data.

For simple data types, Python figures out what data type is best when you create a new variable. An important thing to keep in mind when naming variables is that it's up to you to name them well. There are a number of different data types in Python, but there's no distinction as to how you must name them. This means that it is up to you to give good, descriptive names to your variables.

### Why is that important?

The point of descriptive variable names is to improve readability and understanding of code for both yourself and others. While you may believe that you will never re-use a piece of code, or that if you do you will remember what you were doing, the truth is that you won't. **Good naming practices make all the difference.**

## Creating variables

Variable = Vary + Able = Something which can vary in its value.

- Think of a variable name as a box.
- Think of a variable value as an item in the box.
- Think of defining variable as putting an item in the box.
- Calling the variable means opening the box, which will show the item inside it.

<img src = "https://lab.arts.ac.uk/uploads/images/gallery/2023-08/scaled-1680-/RgkssQLT88g7Q0Lk-image-1692714764115.png" width=400/>



One creates a variable by assigning a value to it:

In [ ]:
# Define a variable called x with some value


# = is an assignment operator.
# The value at left side of = goes to the variable at right side.

<img src = "https://miro.medium.com/v2/resize:fit:640/format:webp/1*nbnwA9n-RebunC2-hEHXuw.png" width = 400>

In [ ]:
# Print the value of x using print() method

As its name suggest, a variable can have its associated value **changed**.

Think of it like replacing the item in the box.

In [ ]:
# Redefine x with some other value and print in the same code cell

print(x)

x = 20   # same variable getting redefined.

print(x)

**NOTE:**: The sequence of output is in the same order as of the sequence of the execution of the code.

In [ ]:
# Run this 2nd.

print(y + 10)

# You will get error. Why?

In [ ]:
# Run this 1st.
y = 6


## Basic data types

Python has eight built-in data types. Four of those are quite simple, in the sense that they can **store a single value**:

* Integers - **int** - Natural numbers which can be counted.
* Floats - **float** - Decimal numbers
* Booleans - **bool** - True/False
* Strings - **str** - Text. Ordered sequence of characters.


The other four are denoted **collections** because they can **store arbitrary numbers of values**. Python's four collection data types are:

* Lists
* Tuples
* Sets
* Dictionaries

*We will see these in next module.*

In [ ]:
# Define some variables with different basic data types

fname = "John"   # strings are defined with single or double quotation marks
Lname = 'Cena'  # strings defined with single quotations
FullName = 'John Cena'  # this is also a string since it's within '' or ""
age = 45        # int
weight = 75.5   # float
celebrity = True   # boolean will have either True or False

# Multiple variables may be defined in a single statement too
x, y, z =

SyntaxError: invalid syntax (ipython-input-1-2806018408.py, line 11)

Points to remember while creating variables:

- Everything in Python is case-sensitive: 'YOU', 'you', 'You', and 'yOu' are all different names in Python
- A variable name must not start with a number.Nnames you define must start with a letter (a-z,A-Z) or underscore (_) and can be followed by any number of letters, digits (0-9), or underscores
- There should not be any space in a variable name.
- Do not use Python reserved keywords as variable name.
- Note that '-', '+', '*', and '/' are used by Python for defining operations on data and cannot be used in names.
- Note also that that the characters '@', '$' and '?' are not used in Python syntax.

In [ ]:
# Priting the first name

print(Fname)

# Why error? Correct the code.

In [ ]:
# Print multiple variables in same code cell. Use print() for each line.
print(fname)
print(Lname)
print(x, y)  # printing multiple variables in a single line

NameError: name 'fname' is not defined

## Arithematic Operations on Variables

### Operations on Numbers

In [ ]:
# Variables can be used for mathematical calculations

print(x * 10 + y - z)  # We have already defined x, y and z

In [ ]:
# Mathematical operations on numbers: Set 1

print(7 + 3)  # addition

print(7 - 3)  # substraction

print(7 * 3)  # multiplication

print(7 / 3)  # division

Next, we will see how to find the quotient, remainder and exponential power.

<img src="https://static.javatpoint.com/programs/images/write-a-program-to-find-the-quotient-and-remainder.png">

In [ ]:
# Mathematical operations on numbers: Set 2

print(25 // 6)  # quotient - floor division

print(25 % 6)  # remainder - Modulo operator

print(6 ** 2)  # power/exponent

#### = vs ==

- = is an assignment operator. It does not give any output, it defines a variables or assigns a value to a variable name.

- == is comparison/equality operators which check is the value/variable on the left is equal to the value/variable on right or not. It gives a boolean output.

<img src= "https://images.surferseo.art/8f7c490f-0902-4cd2-ac1d-aa3b08fca579.png" width = 450>

In [ ]:
# Mathematical operations on numbers: Set 3

print(7 == 3)  # comparison/equality operator. Output - True/False
print(x == 4)  # this is not same as x = 4
print(4 == 4)  # 4 is equal to 4. True or False?
print(4 != 4)  # 4 NOT EQUAL TO 4. True or False?

### Operations on Strings

In [ ]:
# Joining multiple strings without space
print(fname + Lname)     # concatenation or joining two strings

# Joining multiple strings by introducing SPACE as a string
print("Mr. " + fname + " " + Lname)  # here, we are adding space

# Priting mupltiple strings variables with space in between
print("Mr.",fname, Lname)  # here, space will appear by default in output

# We can do addition of strings
# Full name = first name + last name and then print full name
fullname = fname + Lname
print("The fullname is:", fullname)

In [ ]:
# We can multiply a string with a number. It will repeat/reprint the string without space
print(fullname * 3)

In [ ]:
# Other operations are not possible on strings
print(fname + 3)
print(fullname - Lname)

**Counting number is items in a sequence:**

Counting the number of elements/characters in a string

In [ ]:
# len() can be used to count the number if items in a sequence

x = "Python prog"
len(x)

## Type casting : Changing the data type

**Printing data types/class using type()**

**Type casting - changing the data type of a variable**

In [ ]:
x = '5' # it is a string since it's within quotation
print(x)
print(type(x))

In [ ]:
x = int(x)  # converting to int
print(x)
print(type(x))

In [ ]:
x = 5          # int
print(x)
print(type(x))
print()          # printing blank line

x = str(x)          # converting to Str
print(x)
print(type(x))
print()          # printing blank line

x = float(x)          # converting to float
print(x)
print(type(x))
print()          # printing blank line

x = int(x)          # Converting to int
print(x)
print(type(x))
print()          # printing blank line

**ALL INPUTS are of string data type by default.
We must convert them into proper format for calculations.**

In [ ]:
# Taking two numbers and then adding them

x = input("Enter 1st number: ")  # by default, all inputs are of string type
y = input("Enter 2nd number: ")

result = x + y  # since x and y are strings, + will concatenate them together
print(result)

Now, we will try to convert the input number to a number - can be either integer or float.

`x = int(input())`

It can also be written as:

`x = input()
x = int(x)`

In [ ]:
# Taking two numbers and then adding them

x = int(input("Enter 1st number: "))  # converting the input to int
y = int(input("Enter 2nd number: "))

result = x + y
print(result)


# If we input an alphabet then the conversion to int/float will throw error.

# Exercises

##### Question 1: Write a program to that takes the name of the users and shows a welcome message as below:
`Hello, John
How can I help?`

In [ ]:
# Your answer here:

name

##### Question 2: Write a program that to calculate volume of a cylinder.

<img src = "https://dcvp84mxptlac.cloudfront.net/diagrams2/cylinder-volume-formula.png" width = 300>

Formula for a cylinder's volume: **π r² h**

Assume: h = 10cm, r = 2cm, π = 3.14 or 22/7

Sample output:
 `The volume is: 125.6 cm3`

##### Question 3: Write a program to that takes two numbers from users and then show the addition, substraction and checks if the two numbers are same or not.  
Sample output:
###### Enter 1st number: 5
###### Enter 1st number: 3 <br>
###### Addition result: 8.0
###### Substraction result: 2.0
###### Both numbers are same: False

### Exercises completed!

Please refer to the notebooks in Additional Learning folder for a few more concepts/exercises on Basic Data Types